DROP TABLE Category;
DROP TABLE Advert;
DROP TABLE Phone;
DROP TABLE User;

CREATE TABLE User (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(20) NOT NULL 
);

CREATE TABLE Phone (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  number VARCHAR(20) NOT NULL UNIQUE,
  comment VARCHAR(50),
  userId INTEGER NOT NULL,
  CONSTRAINT user_phone_fk FOREIGN KEY (userId) REFERENCES User(id) 
);

CREATE TABLE Advert (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  message VARCHAR(200),
  userId INTEGER NOT NULL,
  CONSTRAINT user_advert_fk FOREIGN KEY (userId) REFERENCES User(id) 
);

CREATE TABLE Category (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL
);